#################################
# TURNILO CONFIG FILE
#
# The following configuration sets up turnilo to connect to the druid datasources/datacubes: pt.probe.global, pt.probe.hbh, and pt.probe.processed
# Reference documentation for parameters: https://allegro.github.io/turnilo/
#################################
port: 9090

customization:
  timezones:
  - America/New_York
  - Etc/UTC
  - Europe/Paris
  - Europe/Zurich

clusters:
  - name: druid
    url: http://localhost:8082
    sourceListScan: disable
    sourceListRefreshOnLoad: false
    sourceListRefreshInterval: 0
    sourceReintrospectOnLoad: false
    sourceReintrospectInterval: 0

dataCubes:
  ################################################
  # DATACUBE pt.probe.global
  ################################################
  - name: pt.probe.global
    title: pt.probe.global
    clusterName: druid
    source: pt.probe.global
    timeAttribute: time
    refreshRule:
      rule: realtime
    defaultTimezone: Europe/Zurich
    defaultDuration: PT10M
    defaultSortMeasure: [count]
    defaultSelectedMeasures: [count]
    defaultPinnedDimensions: []
    introspection: no-autofill
    maxsplits: 3
    attributeOverrides:
      - name: traffic_class
        type: NUMBER

    dimensions:
      - name: time
        title: Time
        kind: time
        granularities: ['PT1S', 'PT10S', 'PT1M', 'PT5M', 'PT30M']
        formula: $__time

      - name: src_node.addr
        title: Src Ipv6 Addr
        formula: ${src_node.addr}

      - name: src_node.node_id
        title: Src Node ID
        formula: ${src_node.node_id}

      - name: snk_node.addr
        title: Snk Ipv6 Addr
        formula: ${snk_node.addr}

      - name: snk_node.node_id
        title: Snk Node ID
        formula: ${snk_node.node_id}

      - name: sid_list
        title: Sid List
        formula: ${sid_list}

      - name: sid_list_full
        title: Sid List Full
        formula: ${sid_list_full}

      - name: nodes_path_list
        title: Nodes Path List
        formula: ${path_info.nodes_path_list}

      - name: path_info.nodes_path
        title: Nodes Path Full
        formula: ${path_info.nodes_path}

      - name: midpoint_count
        title: Midpoint Count
        formula: ${midpoint_count}

      - name: traffic_class
        title: Traffic Class
        formula: ${traffic_class}
        kind: "string"

      - name: flow_label
        title: Flow Label
        formula: ${flow_label}

      - name: sequence_number
        title: Sequence Number
        formula: ${sequence_number}

      - name: src_node.out_interface_id
        title: Src Node Out Interface Id
        formula: ${src_node.out_interface_id}

      - name: src_node.out_interface_name
        title: Src Node Out Interface Name
        formula: ${src_node.out_interface_name}

      - name: snk_node.in_interface_id
        title: Snk Node In Interface Id
        formula: ${snk_node.in_interface_id}

      - name: snk_node.in_interface_name
        title: Snk Node In Interface Name
        formula: ${snk_node.in_interface_name}

      - name: snk_node.tef_sid
        title: Snk Node Tef Sid
        formula: ${snk_node.tef_sid}

      - name: interface_id_path
        title: Interface IDs Path Full
        formula: ${path_info.interface_id_path}

      - name: interface_name_path
        title: Interface Names Path Full
        formula: ${path_info.interface_name_path}

      - name: payload_length
        title: Payload Length
        formula: ${payload_length}
      
        # Add 40bytes for IP header and 14bytes for ETH header
      - name: packet_bytes
        title: Packet Bytes
        formula: ${payload_length}.add(40)   

      - name: hop_limit
        title: Hop Limit
        formula:  ${hop_limit}

      - name: hbh_opt_length
        title: Hop-by-hop Option Length
        formula:  ${hbh_opt_length}

      - name: srh_tag
        title: Srh Tag
        formula: ${srh_tag}

      - name: srh_flag
        title: Srh Flag
        formula: ${srh_flag}

      - name: segments_left
        title: Segments Left
        formula: ${segments_left}

      - name: session_id
        title: Session Id
        formula: ${session_id}

      - name: delay_ms
        title: Delay (ms)
        formula: ${delay_ms}

        # TODO: debug why this doesn't work
      #- name: path_info.delay
      #  title: Delay (ms) python
      #  formula: ${path_info.delay}

      - name: delay_ns
        title: Delay (ns)
        formula: ${delay_ns}


    # Plywood bucketing expressions (https://plywood.imply.io/expressions)
    measures:
      - name: count
        title: Count
        formula: $main.count()

      - name: delay_ms_average
        title: Full Path Delay Average (ms)
        formula: $main.average($delay_ms)
        format: 0,0.000 a

      - name: delay_ms_max
        title: Full Path Delay Max (ms)
        formula: $main.max($delay_ms)
        format: 0,0.000 a

      - name: delay_ms_min
        title: Full Path Delay Min (ms)
        formula: $main.min($delay_ms)
        format: 0,0.000 a

      # Add 40bytes for IP header
      # TO BE CONSISTENT WITH IPFIX: only adding IP Header(40bytes), not counting ETH header(14bytes)
      - name: bps
        title: bps
        formula: $main.sum(${payload_length}.add(40))*8 / ($MillisecondsInInterval / 1000)

      - name: kbps
        title: kbps
        formula: $main.sum(${payload_length}.add(40))*8 / ($MillisecondsInInterval / 1000) /1000

      - name: mbps
        title: mbps
        formula: $main.sum(${payload_length}.add(40))*8 / ($MillisecondsInInterval / 1000) /1000000

#      - name: delay_ns_average
#        title: Delay Average (ns)
#        formula: $main.average($delay_ns)
#        format: 0,0.0 a

  ################################################
  # DATACUBE pt.probe.hbh
  ################################################
  - name: pt.probe.hbh
    title: pt.probe.hbh
    clusterName: druid
    source: pt.probe.hbh
    timeAttribute: time
    refreshRule:
      rule: realtime
    defaultTimezone: Europe/Paris
    defaultDuration: PT1H
    defaultSortMeasure: [count]
    defaultSelectedMeasures: [count]
    defaultPinnedDimensions: []
    introspection: no-autofill
    attributeOverrides:
      - name: traffic_class
        type: NUMBER

    dimensions:
      - name: time
        title: Time
        kind: time
        formula: $__time

      - name: link_info.link_id
        title: Link ID
        formula: ${link_info.link_id}

      - name: link_info.src_node_id
        title: Link Src Node ID
        formula: ${link_info.src_node_id}
      
      - name: link_info.src_interface_name
        title: Link Src Interface Name
        formula: ${link_info.src_interface_name}

      - name: link_info.dst_node_id
        title: Link Dst Node ID
        formula: ${link_info.dst_node_id}

      - name: link_info.dst_interface_name
        title: Link Dst Interface Name
        formula: ${link_info.dst_interface_name}

      - name: src_node.addr
        title: Flow Src Ipv6 Addr
        formula: ${src_node.addr}

      - name: src_node.node_id
        title: Flow Src Node ID
        formula: ${src_node.node_id}

      - name: snk_node.addr
        title: Flow Snk Ipv6 Addr
        formula: ${snk_node.addr}

      - name: snk_node.node_id
        title: Flow Snk Node ID
        formula: ${snk_node.node_id}

      - name: sid_list
        title: Sid List
        formula: ${sid_list}

      - name: sid_list_full
        title: Sid List Full
        formula: ${sid_list_full}

      - name: nodes_path_list
        title: Nodes Path List
        formula: ${path_info.nodes_path_list}

      - name: path_info.nodes_path
        title: Nodes Path Full
        formula: ${path_info.nodes_path}

      - name: midpoint_count
        title: Midpoint Count
        formula: ${midpoint_count}

      - name: traffic_class
        title: Traffic Class
        formula: ${traffic_class}

      - name: flow_label
        title: Flow Label
        formula: ${flow_label}

      - name: sequence_number
        title: Sequence Number
        formula: ${sequence_number}

      - name: snk_node.tef_sid
        title: Flow Snk Node Tef Sid
        formula: ${snk_node.tef_sid}

      - name: interface_id_path
        title: Interface IDs Path Full
        formula: ${path_info.interface_id_path}

      - name: interface_name_path
        title: Interface Names Path Full
        formula: ${path_info.interface_name_path}

      - name: payload_length
        title: Payload Length
        formula: ${payload_length}

      - name: hop_limit
        title: Hop Limit
        formula:  ${hop_limit}

      - name: hbh_opt_length
        title: Hop-by-hop Option Length
        formula:  ${hbh_opt_length}

      - name: srh_tag
        title: Srh Tag
        formula: ${srh_tag}

      - name: srh_flag
        title: Srh Flag
        formula: ${srh_flag}

      - name: segments_left
        title: Segments Left
        formula: ${segments_left}

      - name: session_id
        title: Session Id
        formula: ${session_id}

      - name: link_info.delay
        title: Link Delay (ms)
        formula: ${link_info.delay}

      - name: delay_ms
        title: Full Path Delay (ms)
        formula: ${delay_ms}

    # Plywood bucketing expressions (https://plywood.imply.io/expressions)
    measures:
      - name: count
        title: Count
        formula: $main.count()

      - name: link_info.delay_average
        title: Link Delay Average (ms)
        formula: $main.average(${link_info.delay})
        format: 0,0.000 a

      - name: link_info.delay_max
        title: Link Delay Max (ms)
        formula: $main.max(${link_info.delay})
        format: 0,0.000 a

      - name: link_info.delay_min
        title: Link Delay Min (ms)
        formula: $main.min(${link_info.delay})
        format: 0,0.000 a

      - name: delay_ms_average
        title: Full Path Delay Average (ms)
        formula: $main.average($delay_ms)
        format: 0,0.000 a

      - name: delay_ms_max
        title: Full Path Delay Max (ms)
        formula: $main.max($delay_ms)
        format: 0,0.000 a

      - name: delay_ms_min
        title: Full Path Delay Min (ms)
        formula: $main.min($delay_ms)
        format: 0,0.000 a

      - name: bps
        title: bps
        formula: $main.sum(${payload_length}.add(40))*8 / ($MillisecondsInInterval / 1000)

      - name: kbps
        title: kbps
        formula: $main.sum(${payload_length}.add(40))*8 / ($MillisecondsInInterval / 1000) /1000

      - name: mbps
        title: mbps
        formula: $main.sum(${payload_length}.add(40))*8 / ($MillisecondsInInterval / 1000) /1000000


  ################################################
  # DATACUBE pt.ipfix.processed
  ################################################
  - name: pt.ipfix.processed
    title: pt.ipfix.processed
    clusterName: druid
    source: pt.ipfix.processed
    timeAttribute: time
    maxSplits: 5
    refreshRule:
      rule: realtime
    defaultTimezone: Europe/Zurich
    defaultDuration: PT1H
    defaultSortMeasure: [count]
    defaultSelectedMeasures: [count]
    defaultPinnedDimensions: []
    introspection: no-autofill
    attributeOverrides:

    dimensions:
      - name: time
        title: Time
        kind: time
        formula: $__time

      - name: peer_id
        title: Peer ID
        formula: $peer_id

      - name: ip_src
        title: IPv6 Src
        formula: $ip_src

      - name: ip_dst
        title: IPv6 Dst
        formula: $ip_dst

      - name: link_in
        title: Inbound Link
        formula: $link_in

      #- name: iface_in_avg_delay
      #  title: Inbound Link Avg Delay
      #  formula: $iface_in_avg_delay

      #- name: iface_in_count_considered_for_delay
      #  title: Inbound Link Packets (pt)
      #  formula: $iface_in_count_considered_for_delay

      - name: link_out
        title: Outbound Link
        formula: $link_out

      #- name: iface_out_avg_delay
      #  title: Outbound Link Avg Delay
      #  formula: $iface_out_avg_delay

      #- name: iface_out_count_considered_for_delay
      #  title: Outbound Link Packets (pt)
      #  formula: $iface_out_count_considered_for_delay

      - name: ip_proto
        title: IP Proto
        formula: $ip_proto

      - name: packets
        title: Packets
        formula: $packets

      - name: bytes
        title: Bytes
        formula: $bytes

    # Plywood bucketing expressions (https://plywood.imply.io/expressions)
    measures:
      - name: count
        title: Count
        formula: $main.count()

      - name: iface_in_delay
        title: Inbound Delay Average (ms)
        formula: $main.sum($iface_in_avg_delay.multiply($iface_in_count_considered_for_delay)).divide($main.sum($iface_in_count_considered_for_delay))
        format: 0,0.000 a

      - name: iface_out_delay
        title: Outbound Delay Average (ms)
        formula: $main.sum($iface_out_avg_delay.multiply($iface_out_count_considered_for_delay)).divide($main.sum($iface_out_count_considered_for_delay))
        format: 0,0.000 a

      - name: bps
        title: bps
        formula: $main.sum($bytes)*8 / ($MillisecondsInInterval / 1000)

      - name: kbps
        title: kbps
        formula: $main.sum($bytes)*8 / ($MillisecondsInInterval / 1000) /1000

      - name: mbps
        title: mbps
        formula: $main.sum($bytes)*8 / ($MillisecondsInInterval / 1000) /1000000


  ################################################
  # DATACUBE pt.ipfix.joined
  ################################################
  - name: pt.ipfix.joined
    title: pt.ipfix.joined
    clusterName: druid
    source: pt.ipfix.joined
    timeAttribute: time
    maxSplits: 5
    refreshRule:
      rule: realtime
    defaultTimezone: Europe/Zurich
    defaultDuration: PT1H
    defaultSortMeasure: [count]
    defaultSelectedMeasures: [count]
    defaultPinnedDimensions: []
    introspection: no-autofill
    attributeOverrides:

    dimensions:
      - name: time
        title: Time
        kind: time
        formula: $__time

      - name: ip_src
        title: IPv6 Src
        formula: $ip_src

      - name: ip_dst
        title: IPv6 Dst
        formula: $ip_dst

      - name: src_node
        title: Src Node ID
        formula: $src_node

      - name: mid_node_1
        title: Mid Node 1
        formula: $mid_node_1

      - name: mid_node_2
        title: Mid Node 2
        formula: $mid_node_2

      - name: snk_node
        title: Snk Node ID
        formula: $snk_node

      - name: full_path
        title: Full Path
        formula: $src_node.concat(" - ").concat($mid_node_1).concat(" - ").concat($mid_node_2).concat(" - ").concat($snk_node)

      - name: link_1
        title: Link 1 ID
        formula: $link_1

#      - name: link_1_packets
#        title: Link 1 Packets
#        formula: $link_1_packets
#
#      - name: link_1_bytes
#        title: Link 1 Bytes
#        formula: $link_1_bytes
#
#      - name: link_1_count_considered_for_delay
#        title: Link 1 Count considered for delay
#        formula: $link_1_count_considered_for_delay

      - name: link_2
        title: Link 2 ID
        formula: $link_2

      - name: link_3
        title: Link 3 ID
        formula: $link_3

    # Plywood bucketing expressions (https://plywood.imply.io/expressions)
    measures:
      - name: count
        title: Count
        formula: $main.count()

      - name: full_path_delay_avg
        title: Full Path Delay Average (ms)
        formula: $main.average($full_path_delay_avg)
        format: 0,0.000 a

      - name: bps
        title: bps
        formula: $main.sum($link_1_bytes)*8 / ($MillisecondsInInterval / 1000)

      - name: kbps
        title: kbps
        formula: $main.sum($link_1_bytes)*8 / ($MillisecondsInInterval / 1000) /1000

      - name: link_1_delay_avg
        title: Link 1 Delay Average (ms)
        formula: $main.average($link_1_delay_avg)
        format: 0,0.000 a

      - name: link_1_delay_max
        title: Link 1 Delay Max (ms)
        formula: $main.max($link_1_delay_max)
        format: 0,0.000 a

      - name: link_1_delay_min
        title: Link 1 Delay Min (ms)
        formula: $main.min($link_1_delay_min)
        format: 0,0.000 a

      - name: link_2_delay_avg
        title: Link 2 Delay Average (ms)
        formula: $main.average($link_2_delay_avg)
        format: 0,0.000 a

      - name: link_2_delay_max
        title: Link 2 Delay Max (ms)
        formula: $main.max($link_2_delay_max)
        format: 0,0.000 a

      - name: link_2_delay_min
        title: Link 2 Delay Min (ms)
        formula: $main.min($link_2_delay_min)
        format: 0,0.000 a

      - name: link_3_delay_avg
        title: Link 3 Delay Average (ms)
        formula: $main.average($link_3_delay_avg)
        format: 0,0.000 a

      - name: link_3_delay_max
        title: Link 3 Delay Max (ms)
        formula: $main.max($link_3_delay_max)
        format: 0,0.000 a

      - name: link_3_delay_min
        title: Link 3 Delay Min (ms)
        formula: $main.min($link_3_delay_min)
        format: 0,0.000 a