version: '3'

volumes:
  kafka_zookeeper_data: {}
  kafka_data: {}
  metadata_data: {}
  middle_var: {}
  historical_var: {}
  broker_var: {}
  coordinator_var: {}
  router_var: {}
  druid_shared: {}

services:
  ####################################################
  # Kafka & Zookeeper
  ####################################################
  zookeeper_kafka:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper_kafka
    restart: unless-stopped
    ports:
      - '2181:2181'
    volumes:
      - "kafka_zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    restart: unless-stopped
    ports:
      - '9092:9092'
      - '9093:9093'
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1

      # Add listeners (for inside and outside docker-network)
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper_kafka:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

      # Remove TLS client auth
      - KAFKA_TLS_CLIENT_AUTH=none
      - KAFKA_CLIENT_USER=leo
      - KAFKA_CLIENT_PASSWORD=kafka

      # Retention policy
      - KAFKA_CFG_LOG_RETENTION_HOURS=24
    depends_on:
      - zookeeper_kafka

  ####################################################
  # Apache Druid (TSDB)
  ####################################################
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped 
    volumes:
      - metadata_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=druid
      - POSTGRES_DB=druid

  # Need 3.5 or later for container nodes
  zookeeper_druid:
    container_name: zookeeper_druid
    image: zookeeper:3.5
    restart: unless-stopped 
    ports:
      - "2182:2181"
    environment:
      - ZOO_MY_ID=1

  coordinator:
    image: apache/druid:0.22.1
    container_name: coordinator
    restart: unless-stopped 
    volumes:
      - druid_shared:/opt/shared
      - coordinator_var:/opt/druid/var
      - /home/ethrole1/daisy/docker/druid/samples:/var/tmp/samples
    depends_on: 
      - zookeeper_druid
      - postgres
    ports:
      - "8081:8081"
    command:
      - coordinator
    env_file:
      - /home/ethrole1/daisy/docker/druid/environment

  broker:
    image: apache/druid:0.22.1
    container_name: broker
    restart: unless-stopped 
    volumes:
      - broker_var:/opt/druid/var
      - /home/ethrole1/daisy/docker/druid/samples:/var/tmp/samples
    depends_on: 
      - zookeeper_druid
      - postgres
      - coordinator
    ports:
      - "8082:8082"
    command:
      - broker
    env_file:
      - /home/ethrole1/daisy/docker/druid/environment

  historical:
    image: apache/druid:0.22.1
    container_name: historical
    restart: unless-stopped 
    volumes:
      - druid_shared:/opt/shared
      - historical_var:/opt/druid/var
      - /home/ethrole1/daisy/docker/druid/samples:/var/tmp/samples
    depends_on: 
      - zookeeper_druid
      - postgres
      - coordinator
    ports:
      - "8083:8083"
    command:
      - historical
    env_file:
      - /home/ethrole1/daisy/docker/druid/environment

  middlemanager:
    image: apache/druid:0.22.1
    container_name: middlemanager
    restart: unless-stopped 
    volumes:
      - druid_shared:/opt/shared
      - middle_var:/opt/druid/var
      - /home/ethrole1/daisy/docker/druid/samples:/var/tmp/samples
    depends_on: 
      - zookeeper_druid
      - postgres
      - coordinator
    ports:
      - "8091:8091"
      - "8100-8105:8100-8105"
    command:
      - middleManager
    env_file:
      - /home/ethrole1/daisy/docker/druid/environment

  router:
    image: apache/druid:0.22.1
    container_name: router
    restart: unless-stopped 
    volumes:
      - router_var:/opt/druid/var
      - /home/ethrole1/daisy/docker/druid/samples:/var/tmp/samples
    depends_on:
      - zookeeper_druid
      - postgres
      - coordinator
    ports:
      - "8888:8888"
    command:
      - router
    env_file:
      - /home/ethrole1/daisy/docker/druid/environment